"""
Author: pham cong hoang
Date: 22/10/2021
Problem: Describe the costs and benefits of defining and using a recursive function.
Solution:
Although recursive solutions are often more natural and elegant than their iterative counterparts,
they come with a cost. The run-time system on a real computer, such as the PVM, must devote some overhead
to recursive function calls. At program startup, the PVM reserves an area of memory named a call stack.
For each call of a function, recursive or otherwise, the PVM must allocate on the call stack a small chunk
of memory called a stack frame. In this type of storage, the system places the values of the arguments and
the return address for each function call. Space for the function call’s return value is also reserved
in its stack frame. When a call returns or completes its execution, the return address is used to locate
the next instruction in the caller’s code, and the memory for the stack frame is deallocated. The stack
frames for the process generated by displayRange(1, 3) are shown in Figure 6-4. The frames in the figure
include storage for the function’s arguments only.
"""